- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
- src/main/java/com/uipath/uipathpackage/UiPathPack.java
- src/main/java/com/uipath/uipathpackage/Utility.java
- src/main/resources/config.properties
- src/test/java/com/uipath/uipathpackage/UiPathDeployTest.java
- src/test/java/com/uipath/uipathpackage/UiPathPackTest.java
- src/test/java/com/uipath/uipathpackage/UtilityTest.java
Removed dependency on powershell lib as it was not compatible with output of UiRobot 2019.4 of UiPath
> fix: use own implementation to remove powershell lib

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
- src/main/java/com/uipath/uipathpackage/UiPathPack.java
- src/main/java/com/uipath/uipathpackage/Utility.java
- src/main/resources/config.properties
- src/test/java/com/uipath/uipathpackage/UiPathDeployTest.java
- src/test/java/com/uipath/uipathpackage/UiPathPackTest.java
- src/test/java/com/uipath/uipathpackage/UtilityTest.java
fix: use own implementation to remove powershell lib
> Release v1.0.1 beta merge

- Jenkinsfile
- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
- src/main/java/com/uipath/uipathpackage/UiPathPack.java
- src/main/java/com/uipath/uipathpackage/Utility.java
- src/test/java/com/uipath/uipathpackage/UiPathDeployTest.java
- src/test/java/com/uipath/uipathpackage/UiPathPackTest.java
- src/test/java/com/uipath/uipathpackage/UtilityTest.java
Updated the plugin to work on distributed build.
Deleted Jenkinsfile as it is not being used in JenkinsCI
For automation Run unit tesing, for manual set up a jenkins server and follow the setup guide as per readme.md. Have posted a query in jenkins dev group for the same to write tests for agent. https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/jenkinsci-dev/qmD6BrJAbVg
-- [UI-25542](https://uipath.atlassian.net/browse/UI-25542)
> Updated the plugin to work on distributed build

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
- src/main/java/com/uipath/uipathpackage/UiPathPack.java
- src/main/java/com/uipath/uipathpackage/Utility.java
Removed powershell dependency,instead using launcher to execute powershell commands
> Fixed issue to work with pipeline

- Jenkinsfile
- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
- src/main/java/com/uipath/uipathpackage/UiPathPack.java
- src/main/java/com/uipath/uipathpackage/Utility.java
- src/test/java/com/uipath/uipathpackage/UiPathDeployTest.java
- src/test/java/com/uipath/uipathpackage/UiPathPackTest.java
- src/test/java/com/uipath/uipathpackage/UtilityTest.java
mergeing v1.0.3.beta to master
> Release v1.0.3.beta

- src/main/java/com/uipath/uipathpackage/UiPathAssets.java
- src/main/java/com/uipath/uipathpackage/UiPathRunJob.java
> Throw on Non-Windows OS for RunJob and ManageAssets

- build.steps.template.yml
- job.ci.build.yml
https://uipath.atlassian.net/browse/TS-1338
> Enable easier security scan

- .vsts-ci-security.yml
- azure-pipelines.yml
- stage.security.yml
> Security Scan

- build.steps.template.yml
- job.ci.build.yml
- pom.xml
- src/main/resources/config.properties
- src/test/java/com/uipath/uipathpackage/UiPathDeployTests.java
Updated the uipcli version to 1.0.7751.16250
> Incremented uipath jenkins plugin version to 2.3.2

- azure-pipelines.yml
- job.ci.test.template.yml
- stage.test.template.yml
Updated the test cases structure
Added multiple TCs
> Added multi stage for tests

- pom.xml
> Add missing help files into the hpi

- azure-pipelines.yml
- src/main/resources/config.properties
- stage.test.template.yml
Added pipeline tests for GetFolderFeedId method via token & external app
> Updated CLI version and external app mechanism

- pom.xml
- src/main/resources/config.properties
- upgraded CLI version from 1.0.7838.10614 to 1.0.7881.13724
- upgraded Jenkins Plugin version from 2.3.3-SNAPSHOT to 2.4.0-SNAPSHOT
> upgraded version for cli and jenkins plugin

- pom.xml
- src/main/resources/config.properties
Hotfix for Entry point fix
To be tested in preview
> Hotfix for Entry point issue

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathRunJob.java
- src/main/java/com/uipath/uipathpackage/entries/authentication/ExternalAppAuthenticationEntry.java
- src/main/java/com/uipath/uipathpackage/entries/job/TestAutomationJobTypeEntry.java
- src/main/java/com/uipath/uipathpackage/util/JobType.java
- src/main/java/com/uipath/uipathpackage/util/Utility.java
- src/main/resources/com/uipath/uipathpackage/Messages.properties
- src/main/resources/config.properties
- src/test/java/com/uipath/uipathpackage/UiPathRunJobTests.java
This PR will contain all the changes that are going in the 2.7 release , also this PR will contain the version bump changes for the latest CLI to be used and the individual version bump for our different packs.
NOTE : This has to be merged only after confirmation of the latest versions of the CLI and the changes going in.
[TS-1682	: Support External App Authentication for on-premise OR](https://uipath.atlassian.net/browse/TS-1682)
[TS-1649	: Support Test Robots license in 'RunJob' task](https://uipath.atlassian.net/browse/TS-1649)
[TS-1629	: Standard Output log in junit result should include a link to Test Case logs from Orchestrator](https://uipath.atlassian.net/browse/TS-1629)
[TS-1628	: Add Test Case variation enumerator into Test Case result …
> 2.7 Release

- pom.xml
- src/main/resources/config.properties
This PR Contains the updated CLI version containing fixes for the JIRAs mentioned below.
https://uipath.atlassian.net/browse/TS-1648
https://uipath.atlassian.net/browse/TS-1658
https://uipath.atlassian.net/browse/TS-1594
https://uipath.atlassian.net/browse/TS-1670
https://uipath.atlassian.net/browse/TS-1726
https://uipath.atlassian.net/browse/TS-1740
https://uipath.atlassian.net/browse/TS-1741
Testing has been done over Jenkins test server and with unit tests.
> Updated CLI and bumped up version to 2.8

- pom.xml
- src/main/resources/config.properties
This PR Contains hotfixes for below mentioned customer issues.
https://uipath.atlassian.net/browse/TS-1752
https://uipath.atlassian.net/browse/TS-1751
Tested over pipeline using preview builds.
> Release v2.8.1

- pom.xml
- src/main/java/com/uipath/uipathpackage/entries/authentication/ExternalAppAuthenticationEntry.java
- src/main/java/com/uipath/uipathpackage/models/AuthenticatedOptions.java
- src/main/java/com/uipath/uipathpackage/util/Utility.java
- src/main/resources/com/uipath/uipathpackage/entries/authentication/ExternalAppAuthenticationEntry/config.jelly
- src/main/resources/com/uipath/uipathpackage/entries/authentication/ExternalAppAuthenticationEntry/config.properties
- src/main/resources/config.properties
This PR contains changes we are pushing out for our 2.9 release.
https://uipath.atlassian.net/browse/TS-1756
Tested over the preview build 
creating entirely new service connection for paas deployments.
checked for existing external app service connections.
For both scenarios was able to pack and deploy to the respective folders.
> Release v2.9

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathTest.java
- src/main/java/com/uipath/uipathpackage/models/TestOptions.java
- src/main/resources/com/uipath/uipathpackage/UiPathTest/config.jelly
- src/main/resources/com/uipath/uipathpackage/UiPathTest/config.properties
- src/main/resources/config.properties
This PR contains updated CLI version fixing the issues we are going to release in v2.9.1
https://uipath.atlassian.net/browse/TS-1787
https://uipath.atlassian.net/browse/TS-1788
https://uipath.atlassian.net/browse/TS-1824
https://uipath.atlassian.net/browse/TS-1798
https://uipath.atlassian.net/browse/TS-1802
> Release v2.9.1

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathTest.java
- src/main/java/com/uipath/uipathpackage/models/TestOptions.java
- src/main/resources/com/uipath/uipathpackage/UiPathTest/config.jelly
- src/main/resources/com/uipath/uipathpackage/UiPathTest/config.properties
- src/main/resources/config.properties
This PR syncs develop from master after releasing v2.9.1
> Post Release v2.9.1 Sync

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathAssets.java
- src/main/java/com/uipath/uipathpackage/UiPathRunJob.java
- src/main/java/com/uipath/uipathpackage/UiPathTest.java
- src/main/java/com/uipath/uipathpackage/entries/authentication/ExternalAppAuthenticationEntry.java
- src/main/resources/config.properties
This PR syncs the changes from  master to develop post v.2.9.2 release.
> sync develop with master post v2.9.2 release

- azure-pipelines.yml
- stage.test.template.yml
As we no longer support OR versions 19.10 & 18.4 . removing the relevant UTs now.
> TS-1896 | Removed Deprecated UTs

- src/main/resources/config.properties
Updating the CLI version to the latest one.
We used the CLI version generated from here : https://uipath.visualstudio.com/Extensions/_build/results?buildId=2935033&view=results
> Updating the CLI version

- pom.xml
- src/main/resources/config.properties
- Containing cli version upgrade, fixing discovery of project Json nested inside different projects.
- Added more projects as a part of integration tests in pipeline.
https://uipath.atlassian.net/browse/TS-2012
> Update CLI version containing fix for TS-2012

- pom.xml
- src/main/resources/config.properties
This is the release PR for ADO plugins containing the changes for below mentioned JIRA items.
Packages are getting deployed as Library (windows project) [TS-2012](https://uipath.atlassian.net/browse/TS-2012)
[ADO] | Disable Caching of CLI NUGET in hostedtoolcache directory [TS-2017](https://uipath.atlassian.net/browse/TS-2017)
> Release v2.11

- job.ci.build.yml
- pom.xml
- src/main/java/com/uipath/uipathpackage/models/AssetsOptions.java
- src/main/java/com/uipath/uipathpackage/models/AuthenticatedOptions.java
- src/main/java/com/uipath/uipathpackage/models/DeployOptions.java
- src/main/java/com/uipath/uipathpackage/models/JobOptions.java
- src/main/java/com/uipath/uipathpackage/models/PackOptions.java
- src/main/java/com/uipath/uipathpackage/models/TestOptions.java
As the Jenkins changes has been done 3-4 months back, we have to take care of the new changes now. Now, while building/testing we found out that caffeine API was needed. Hence, we have made the changes and tested it.
[TS-2101](https://uipath.atlassian.net/browse/TS-2101) Add/Update the caffeine API for the Jenkins Build & Test
https://uipath.visualstudio.com/Plugins.Jenkins/_build/results?buildId=3578012&view=results
> Fix/update caffeine api for the build & test of Jenkins plugin

- pom.xml
This PR syncs the changes from the master to develop post v3.0 release.
> [SYNC DEVELOP] Synching develop with master post v3.0

- CODEOWNERS
Adding @al3xanndru as the owner of this repository.
**Added:**
- Alexandru Groza (@al3xanndru )
**Kept Same:**
- Ganesh Borle (@ganeshborle)
**Removed:**
- Amol Awate (@amoluipath)
- Rishi Singh (@rishi-104276)
> Update CODEOWNERS with the new Owners (Alexandru Groza - @al3xanndru)

- pom.xml
- src/main/java/com/uipath/uipathpackage/UiPathTest.java
Fix build dependencies needed for 4.0 release.
To release Jenkins Plugin v4.0.
E2E tests.
> Merge to jenkinsci repo from forked repo [AUOPS-4287]
